# Generated by Django 2.2.10 on 2020-03-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('Day1', models.CharField(blank=True, max_length=256, null=True)),
                ('Day2', models.CharField(blank=True, max_length=256, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('exam', models.DateTimeField(blank=True, null=True)),
                ('ta_day', models.CharField(blank=True, max_length=256, null=True)),
                ('ta_time', models.TimeField(blank=True, null=True)),
                ('semester', models.CharField(blank=True, max_length=256, null=True)),
                ('department', models.ForeignKey(default='MCS', on_delete=django.db.models.deletion.CASCADE, to='src.Department')),
                ('professor', models.ForeignKey(default='hich', on_delete=django.db.models.deletion.CASCADE, to='src.Professor')),
            ],
        ),
    ]
