# Generated by Django 2.2.10 on 2020-03-27 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(default='MCS', on_delete=django.db.models.deletion.CASCADE, to='src.Department')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=256, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('Day1', models.CharField(blank=True, max_length=256, null=True)),
                ('Day2', models.CharField(blank=True, max_length=256, null=True)),
                ('exam', models.DateTimeField(blank=True, null=True)),
                ('ta_day', models.CharField(blank=True, max_length=256, null=True)),
                ('ta_time', models.TimeField(blank=True, null=True)),
                ('group', models.IntegerField(default=1)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.Course')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=256, null=True)),
                ('course', models.ManyToManyField(to='src.SemesterCourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
