# Generated by Django 2.2.10 on 2020-03-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20200327_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semestercourse',
            old_name='Day1',
            new_name='day1',
        ),
        migrations.RenameField(
            model_name='semestercourse',
            old_name='Day2',
            new_name='day2',
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='course',
            new_name='courses',
        ),
    ]
