# Generated by Django 2.2.10 on 2020-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20200328_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
