# Generated by Django 2.2.10 on 2020-04-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_semestercourse_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestercourse',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
