# Generated by Django 2.2.10 on 2020-04-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_semestercourse_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestercourse',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semestercourse',
            name='start_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
