# Generated by Django 2.2.10 on 2020-05-08 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('src', '0010_auto_20200429_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('req_passed_units', models.IntegerField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserCourse',
            new_name='UserSchedule',
        ),
        migrations.RemoveField(
            model_name='department',
            name='table_count',
        ),
        migrations.RemoveField(
            model_name='userpassed',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userpassed',
            name='is_passed',
        ),
        migrations.AddField(
            model_name='course',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpassed',
            name='courses',
            field=models.ManyToManyField(to='src.Course'),
        ),
        migrations.AddField(
            model_name='userpassed',
            name='units',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='src.ChartTable'),
        ),
        migrations.AddField(
            model_name='charttable',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.Department'),
        ),
    ]
