# Generated by Django 2.2.10 on 2020-05-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_auto_20200508_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpassed',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
