# Generated by Django 2.2.10 on 2020-05-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_charttable_req_not_stared_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestercourse',
            name='exam',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
