# Generated by Django 2.2.10 on 2020-06-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_auto_20200522_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestercourse',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='userschedule',
            name='semester',
        ),
    ]
